### ISSUE TITLE
Make software more generic and reusable

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_account#10]
The software is right now pretty Pleio-branded. As our friends from Canada would like to use this piece of software as well, we should make all branded stuff an option. We should think about a plan to attack this problem.

**Comment by piet0024** [comment]
I'd like to start taking a look at making a generic template for the login. We'll use the django template. 
I've been looking at projects like: https://semantic-ui.com/
It's sleek and generic and it has a react library in development too! https://react.semantic-ui.com/introduction
Let me know what you think!

**Comment by AadSchippers** [comment]
In branch newstyle the following improvements have been implemented to address this issue:

Appearance:
These settings controle the appearance of the site:
SITE_TITLE = 'Pleio_account'
SITE_LOGO = 'images/logo.svg'
SITE_FAVICON = '/static/images/favicon.png'

Functionality:
1 Suspicious login
When a user has logged in from a location he has not used before an email will be send to that user. This behaviour can be controlled with setting SEND_SUSPICIOUS_BEHAVIOR_WARNINGS = True / False

2 Google reCAPTCHA
It's possible to add Google reCAPTCHA to your site. To do that you must register the site at https://www.google.com/recaptcha/admin. Then add the generated API keys to your settings:

(With the following test keys, you will always get No CAPTCHA and all verification requests will pass.)
GOOGLE_RECAPTCHA_SITE_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
GOOGLE_RECAPTCHA_SECRET_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

When those API keys are present in settings, Google reCAPTCHA
- Is always present on register page.
- Will be present on login page when from that IP adress more than RECAPTCHA_NUMBER_INVALID_LOGINS during the last RECAPTCHA_MINUTES_THRESHOLD have occurred.

**Comment by markwooff** [comment]
@AadSchippers that sounds great. I'm just curious if these customizations have to be done in the `config.py` file or if they can be set through the Django admin panel?

Same question for the reCAPTCHA API fields. Thanks!

**Comment by AadSchippers** [comment]
Hi @markwooff, sorry for the late reply.

Currently all settings mentioned above have to be set in config.py. 

Although it is possible to add them to the admin panel we don't feel the need to do so. We believe that these settings are part of the installation and configuration process and that they are not likely to change often once set.

**Comment by bartjkdp** [comment]
Just wanted to add to that, we are currently implementing SAML support. Pleio connects to dozens of SAML providers, so this configuration changes very often (for us at least). We are thinking of making SAML Identity Providers configurable from the admin panel, so our user support team can manage them without operations support. What do you think?

**Comment by markwooff** [comment]
Thanks for the answer @AadSchippers, I suppose we have different views on this. You guys have created a great app here & there may be others besides Pleio & GCTools who would want to use it in the future 👍 

@piet0024 has been doing some work on creating an admin section for customization & branding that we'd be happy to share back upstream.

**Comment by markwooff** [comment]
@bartjkdp that may be a good topic to discuss in your SAML issue: https://github.com/Pleio/pleio_account/issues/3

**Comment by bartjkdp** [comment]
Software for now is more customizable through config parameters. We would be more then happy to accept a pull-request for customization through the admin.

**Comment by markwooff** [comment]
@bartjkdp we've implemented an admin panel section for customizing the frontend of the site. Will make a PR and hope it doesn't conflict with your changes 👍

**Comment by bartjkdp** [comment]
We will make it work 👍
