### ISSUE TITLE
When the user changes the e-mail address, the user first has to validate the change before e-mail is changed

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_account#21]

**Comment by AadSchippers** [comment]
In branch newstyle this has been addressed. When a user name and / or email address has been changed on the profile page, the user has to identify him- or herself with their password.

**Comment by bartjkdp** [comment]
The problem is not the password but the validation of the new e-mail. So when a users changes his e-mail, the user would get an e-mail with a validation link on his new address to confirm the address change.

You could use the [Django signing](https://docs.djangoproject.com/en/2.0/topics/signing/) (with max_age) for that.

**Comment by markwooff** [comment]
We had to build this exact login into our Elgg registration plugin so that users with authorized email addresses could not change their email to a non-authorized address. The address change is only made once they validate via email.

**Comment by bartjkdp** [comment]
It would be super nice that - during a pending change - there is a small text under password e-mail field:

    There is a pending change of your email to <new_email>. Please check your inbox to validate the change. Click here to resend the confirmation e-mail.

**Comment by AadSchippers** [comment]
Ah, my bad I misunderstood. Since Wednesday is my day off, I will see to it Thursday.

**Comment by AadSchippers** [comment]
I've changed the behaviour to what I understand is desired. ;)

See https://drive.google.com/open?id=1oOroq0jRzGLmZ8IcAmLaByFMa_MKc8sp for a demo.

**Comment by bartjkdp** [comment]
This looks absolutely great! Two minor things:

- Think when you change the URL to change-email instead of changeemail, it will be a bit more readable.
- Could we introduce some kind of messaging, like [Bootstrap Alerts](https://v4-alpha.getbootstrap.com/components/alerts/)? In this way we can send a user a "success message" like "The e-mailaddress changed succesfully". I think @Duncank could do some designing first on that. Django ships with a very convenient [messages framework](https://docs.djangoproject.com/en/2.0/ref/contrib/messages/) that you can use for this.

**Comment by AadSchippers** [comment]
- I will amend to URL to change-email tomorrow

-  Adding service messages sound great to me.

**Comment by AadSchippers** [comment]
@Duncank thanks. 
Style 'messages correct' have been implemented for password and e-mail adress changed messages.

**Comment by bartjkdp** [comment]
This is implemented.
