### ISSUE TITLE
Redirect_uri is not being used during authentication

### ISSUE THREAD

**Issue by markwooff** [Pleio/pleio_account#33]
When prompted to login from one application, the `redirect_uri` is not being used to redirect the user back to the application. The user is redirected to the `/profile/` page - perhaps the `LOGIN_REDIRECT_URL` is overriding?

**Comment by lucbelliveau** [comment]
The logout redirect URI is also not respected.

**Comment by AadSchippers** [comment]
@markwooff it was even worse ;) After a successful login user was always redirected to `/profile` no matter what value `LOGIN_REDIRECT_URL` contains.

Sorted now.

**Comment by markwooff** [comment]
Thanks @AadSchippers! Will be testing these changes out today.

**Comment by bartjkdp** [comment]
@markwooff @AadSchippers just merged in our new style, so I think the problems should be solved now.

**Comment by markwooff** [comment]
Thanks all!
