### ISSUE TITLE
Emailvalidator amendment

### ISSUE THREAD

**Issue by AadSchippers** [Pleio/pleio_account#34]
Hi @markwooff, @lucbelliveau

At Pleio we allow for both civil servants and citizens to join. Civil servants will be labeled with a green "governement"-badge next to their name. We were wondering whether it would be possible to slightly amend the emailvalidator app to accommodate for this. We were thinking of adding a settings parameter `ALLOW_FOR_ALL_EMAIL_ADRESSES`. When this setting is `True` no email validation is needed. In all other cases the behaviour of the emailvalidator app will be unchanged. 

When this would be implemented we would be able to allow for all email adresses to signup and use `is_email_valid` to determine whether the email address belongs to a civil servant or not.

What are your thoughts about this?

**Comment by markwooff** [comment]
I don't see any problem with this since the new param will be used for overriding the base functionality & is optional to those setting it up 👍

**Comment by lucbelliveau** [comment]
Something smells funny about this feature flag to me... maybe I'm thinking of potential use cases that would never happen, but still... 

I recommend instead adding a few methods to the email validator app to get a list of groups the user belongs too...  in your use case, a simple group count > 1 would indicate the user is a civil servant...   This way the email validator app can keep doing what its doing... all that is needed is a catchall rule in its own group...(which is what you have now right?)   It would also add some flexibility... for example if you wanted to differentiate between federal and municipal... (if it's a thing over there)...  

I'd be happy to add those metods if you want...

**Comment by AadSchippers** [comment]
That's sounds great @lucbelliveau Looking forward to it. :)

**Comment by AadSchippers** [comment]
This has been implemented.
