### ISSUE TITLE
Registration form not working

### ISSUE THREAD

**Issue by markwooff** [Pleio/pleio_account#35]
Not sure if it's due to the latest code change, but I'm unable to complete the registration process. Could you confirm this?

**Comment by bartjkdp** [comment]
This seems to be a problem when you don't have Google Recaptcha enabled. Will commit a patch shortly.

**Comment by bartjkdp** [comment]
Think this will fix it, see f78cdd

**Comment by markwooff** [comment]
Success! Thanks for the quick fix @bartjkdp

**Comment by markwooff** [comment]
@bartjkdp looks like I was running off an old image.. just tried again this morning and the latest commit seems to have broken something :S

**Comment by bartjkdp** [comment]
Could you provide some error details?

**Comment by markwooff** [comment]
```AttributeError at /register/
'Settings' object has no attribute 'EXTERNAL_HOST'```

```Error during template rendering
In template /app/core/templates/emails/register.txt, error at line 8```

**Comment by bartjkdp** [comment]
This is nothing related to the commit. Some additional settings have been added to the config.py, check out config.example.py

**Comment by bartjkdp** [comment]
In this case, the ```EXTERNAL_HOST``` attribute is used for determining the full URL of the server. We decided to make this configurable in ```config.py```.

**Comment by markwooff** [comment]
Thanks for the info @bartjkdp - will take a look at the example config file for the new attributes. Will close this issue again.

**Comment by bartjkdp** [comment]
No problems, thanks for reporting 👍
