### ISSUE TITLE
Improve UI/UX design

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_account#6]

**Comment by lucbelliveau** [comment]
I noticed the validation errors on the registration page (maybe in other places but I didn't test) isn't styled by materialize... I was going to fix it but I remembered this issue...  Is it still worth it for me to submit a PR or this, or has the UI redesign made this type of change irrelevant?

**Comment by bartjkdp** [comment]
Thanks @lucbelliveau . In the newstyle branch we are currently working on UI/UX improvements. @Duncank also fixes form validation styling there.

**Comment by bartjkdp** [comment]
This is merged in :)
